### ISSUE TITLE
postfix different domain same name collision?

### ISSUE THREAD

**Issue by divinity76** [flurdy/flurdy.com-docs#12]
(not sure exactly where to discuss this, if this is the wrong place then please let me know)

i haven't actually tried a flurdy.com/docs/postfix/ setup yet, but it states:

> setting up a mail server with unlimited users and domains

yet reading through it, it seems apparent that the setup does not support 2 people with the same email name on 2 different domains, is that correct? for example, lets say you have "John Doe" at john@doe.com and you have "John Moe" at john@moe.com , this setup would not be able to support both at the same time, right? john@moe.com's inbox would collide with john@doe.com's inbox? if that's the case, then the `unlimited users and domains` claim looks.. overpromised? (btw English isn't my first language)

(seems like it could be fixed by using a `/var/mail/virtual/%d/%u` scheme instead of a `/var/mail/virtual/%u` scheme, but that isn't the case as of the 14'th edition)

**Comment by flurdy** [comment]
Nope, you can put whatever you want in the maildir column of the users. So yes the examples for simplicity suggest only their alias, but it can be anything.

If you take a look in https://flurdy.com/docs/postfix/#data_add as the sql that adds entries to users can be changed to include a domain if you want:

`INSERT INTO users (id,name,maildir,crypt) VALUES
	('xandros@blobber.org','xandros','blobber.org/xandros/',encrypt('apassword', CONCAT('$5$', MD5(RAND()))) ),
	('vivita@blobber.org','vivita','blobber.org/vivita/', encrypt('anotherpassword', CONCAT('$5$', MD5(RAND()))) );`

For my production mail servers I usually have this expanded to also include an owner, e.g. `/var/mail/virtual/john/example.com/louise`. But the path beyond virtual can be anything as long as the maildir column ends in a `/`.

**Comment by divinity76** [comment]
Thanks for clearing that up!

**Comment by flurdy** [comment]
As for this being the place to discus, 🤷🏻‍♂️ . 

To be fair if there is a problem with the howto then this is the place, though in this case it was just a usage problem, but that is not easy to know initially. A chicken and egg problem.

Previously the Ubuntu forums were a good place to discuss, there have been a lot of messages there over the time, especially on the threads for this howto. However, perhaps stackoverflow or reddit are better locations these days for contributions from others, as I am normally rubbish in responding in a timely matter. Today was an exception 😄
